name: React Native CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest # iOS builds require macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Android app
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Install CocoaPods
        run: |
          brew install cocoapods
          pod setup

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -workspace AwesomeProject.xcworkspace -scheme AwesomeProject -sdk iphonesimulator -configuration Release

          - name: Install Firebase CLI
          run: npm install -g firebase-tools
  
      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute ios/build/AwesomeProject.ipa \
            --app 1:267279363533:ios:68749d520f1004b968a884 \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "testers"
          firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
           --app 1:267279363533:android:c302faf920e2cd6968a884 \
           --token ${{ secrets.FIREBASE_TOKEN }} \
           --groups "testers"

      