name: React Native CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest # iOS builds require macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install CocoaPods
        run: |
          brew install cocoapods
          pod setup

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install

      - name: Install Apple Certificate and Provisioning Profile
        env:
            BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
            P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
            PROVISION_PROFILE_BASE64: ${{ secrets.PROVISION_PROFILE_BASE64 }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
            CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
            PROFILE_PATH=$RUNNER_TEMP/build_profile.mobileprovision
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
  
            echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
            echo "$PROVISION_PROFILE_BASE64" | base64 --decode -o $PROFILE_PATH

            UUID=$(grep UUID -A1 -a "$PROFILE_PATH" | grep -io "[-A-F0-9]\{36\}")
            echo "PROFILE_UUID=$UUID" >> $GITHUB_ENV
            echo "Profile UUID: $UUID"
  
            security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
  
            security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
            security list-keychain -d user -s $KEYCHAIN_PATH
  
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp $PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build and Archive iOS App
        working-directory: ios
        run: |
              xcodebuild -workspace AwesomeProject.xcworkspace \
                         -scheme AwesomeProject \
                         -configuration Release \
                         -archivePath $RUNNER_TEMP/AwesomeProject.xcarchive \
                         -destination "generic/platform=iOS" \
                         CODE_SIGN_STYLE=Manual \
                         CODE_SIGN_IDENTITY="iPhone Distribution" \
                         PROVISIONING_PROFILE="${{ env.PROFILE_UUID }}" \
                         archive || { echo "Archive failed"; exit 1; }
              ls -l $RUNNER_TEMP/
              xcodebuild -exportArchive \
                         -archivePath $RUNNER_TEMP/AwesomeProject.xcarchive \
                         -exportOptionsPlist ExportOptions.plist \
                         -exportPath $RUNNER_TEMP/ipa || { echo "Archive failed"; exit 1; }

      - name: Upload ios to Firebase App Distribution
        run: |
          firebase appdistribution:distribute ios/build/AwesomeProject.ipa \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "ios-testers"

  

      
