name: React Native CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest # iOS builds require macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Build Android app
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload android to Firebase App Distribution
        run: |
          firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
            --app 1:267279363533:android:c302faf920e2cd6968a884 \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "testers"
  
  

      